version: "2.2"

services:
  mqtt:
    image: eclipse-mosquitto:1.6
    ports:
      - "1883:1883"

  fog:
    build:
      context: .
      dockerfile: docker/fog.Dockerfile
    depends_on:
      - mqtt
    environment:
      - PYTHONUNBUFFERED=1
      - mqtt_broker=mqtt
    ports:
      - "8000:8000"
    command: uvicorn fog.server:app --host 0.0.0.0 --port 8000


  cloud:
    build:
      context: .
      dockerfile: docker/cloud.Dockerfile
    depends_on:
      - fog
    ports:
      - "8501:8501" #streamlit address
